require_relative '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@8.3.4/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@8.3.4/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@8.3.4_@capacitor+core@8.3.4/node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseApp', :path => '../../../node_modules/.pnpm/@capacitor-firebase+app@8.2.0_@capacitor+core@8.3.4_firebase@12.12.0/node_modules/@capacitor-firebase/app'
  pod 'CapacitorFirebaseMessaging', :path => '../../../node_modules/.pnpm/@capacitor-firebase+messaging@8.2.0_@capacitor+core@8.3.4_firebase@12.12.0/node_modules/@capacitor-firebase/messaging'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@8.1.0_@capacitor+core@8.3.4/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../node_modules/.pnpm/@capacitor+camera@8.2.0_@capacitor+core@8.3.4/node_modules/@capacitor/camera'
  pod 'CapacitorPreferences', :path => '../../../node_modules/.pnpm/@capacitor+preferences@8.0.1_@capacitor+core@8.3.4/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../node_modules/.pnpm/@capacitor+push-notifications@8.0.3_@capacitor+core@8.3.4/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../node_modules/.pnpm/@capacitor+share@8.0.1_@capacitor+core@8.3.4/node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
