-- Add description column to formats table
ALTER TABLE `formats` ADD COLUMN `description` varchar(255) NULL AFTER `type`;

-- Populate descriptions for all existing formats
UPDATE `formats` SET `description` = 'Completa tantas rondas como puedas en el tiempo asignado' WHERE `name` = 'AMRAP';
UPDATE `formats` SET `description` = 'Varias rondas de AMRAP con descanso entre cada una' WHERE `name` = 'AMRAP Series';
UPDATE `formats` SET `description` = 'Un ejercicio por minuto, el tiempo restante es descanso' WHERE `name` = 'EMOM';
UPDATE `formats` SET `description` = 'Ejercicios encadenados sin soltar la barra' WHERE `name` = 'Complex';
UPDATE `formats` SET `description` = '20 segundos de trabajo maximo, 10 de descanso, 8 rondas' WHERE `name` = 'Tabata';
UPDATE `formats` SET `description` = 'Intervalos de trabajo y descanso alternados' WHERE `name` = 'HIIT';
UPDATE `formats` SET `description` = 'Intervalos de trabajo y descanso con duracion configurable' WHERE `name` = 'Interval Training';
UPDATE `formats` SET `description` = 'Completa todos los ejercicios lo mas rapido posible' WHERE `name` = 'For Time';
UPDATE `formats` SET `description` = 'Lista larga de ejercicios, se completan uno tras otro sin repetir' WHERE `name` = 'Chipper';
UPDATE `formats` SET `description` = 'Empieza y termina con un ejercicio especifico, el trabajo va en el medio' WHERE `name` = 'Buy-in / Cash-out';
UPDATE `formats` SET `description` = 'Grupos cortos de repeticiones con pausas entre cada grupo' WHERE `name` = 'Cluster';
UPDATE `formats` SET `description` = 'Las repeticiones suben o bajan con cada ronda' WHERE `name` = 'Ladder';
UPDATE `formats` SET `description` = 'Realiza todas las repeticiones sin parar' WHERE `name` = 'Unbroken Reps';
UPDATE `formats` SET `description` = 'Dos ejercicios que se alternan por rondas' WHERE `name` = 'Couplet';
UPDATE `formats` SET `description` = 'Tres ejercicios que se alternan por rondas' WHERE `name` = 'Triplet';
UPDATE `formats` SET `description` = 'Busca el maximo peso posible en el ejercicio' WHERE `name` = 'For Max (Carga)';
UPDATE `formats` SET `description` = 'Busca la mayor cantidad de repeticiones posibles' WHERE `name` = 'For Max (Reps)';
UPDATE `formats` SET `description` = 'Busca sostener el ejercicio la mayor cantidad de tiempo' WHERE `name` = 'For Max (Tiempo)';
UPDATE `formats` SET `description` = 'Completa el trabajo dentro del limite de tiempo establecido' WHERE `name` = 'Time Cap';
UPDATE `formats` SET `description` = 'Cada minuto agregas una repeticion hasta que no puedas completar en el minuto' WHERE `name` = 'Death By';
UPDATE `formats` SET `description` = 'Cada minuto agregas una repeticion sin cortar, hasta fallar' WHERE `name` = 'Death By Unbroken';
UPDATE `formats` SET `description` = 'Un companero trabaja mientras el otro descansa, van alternando' WHERE `name` = 'I Go, You Go';
UPDATE `formats` SET `description` = 'Acumula el volumen total indicado a tu propio ritmo' WHERE `name` = 'Accumulate X';
UPDATE `formats` SET `description` = 'Workout clasico con estandar de rendimiento conocido' WHERE `name` = 'Benchmark';
UPDATE `formats` SET `description` = 'Workout clasico con nombre propio de la comunidad' WHERE `name` = 'Benchmark WOD';
UPDATE `formats` SET `description` = 'Escalera con cambios de direccion: sube, baja, y vuelve a subir' WHERE `name` = 'Broken Ladder';
UPDATE `formats` SET `description` = 'Circuito grupal donde cada persona rota de estacion' WHERE `name` = 'Circuito cooperativo';
UPDATE `formats` SET `description` = 'Series con peso decreciente hasta el fallo' WHERE `name` = 'Drop Set';
UPDATE `formats` SET `description` = 'Combina EMOM con un segmento final contrarreloj' WHERE `name` = 'EMOM + For Time';
UPDATE `formats` SET `description` = 'Un ejercicio cada X segundos, descansas lo que te sobre' WHERE `name` = 'Every X Seconds';
UPDATE `formats` SET `description` = 'Secuencia guiada de movimientos continuos sin pausa' WHERE `name` = 'Flow Guiado';
UPDATE `formats` SET `description` = 'Enfocate en la calidad del movimiento, no en la velocidad' WHERE `name` = 'For Quality';
UPDATE `formats` SET `description` = 'Practica tecnica con carga liviana y atencion al detalle' WHERE `name` = 'For Tech';
UPDATE `formats` SET `description` = 'Workout en honor a un heroe, generalmente largo e intenso' WHERE `name` = 'Hero WOD';
UPDATE `formats` SET `description` = 'Escalera de repeticiones agrupada en bloques' WHERE `name` = 'Ladder Block';
UPDATE `formats` SET `description` = 'Escalera rapida con pocas repeticiones por escalon' WHERE `name` = 'Ladder corta';
UPDATE `formats` SET `description` = 'Un ejercicio cada 2 o 3 minutos, descansas lo que sobre' WHERE `name` = 'On the 2:00 / 3:00';
UPDATE `formats` SET `description` = 'Formato abierto estilo competencia con estandares de movimiento' WHERE `name` = 'Open Style';
UPDATE `formats` SET `description` = 'Las repeticiones suben hasta un pico y luego bajan' WHERE `name` = 'Pyramid';
UPDATE `formats` SET `description` = 'Series cortas con micro-descansos para acumular mas volumen' WHERE `name` = 'Rest-Pause';
UPDATE `formats` SET `description` = 'Un solo ejercicio trabajado en multiples series' WHERE `name` = 'Singlet';
UPDATE `formats` SET `description` = 'Prioriza completar las tareas asignadas sin importar el tiempo' WHERE `name` = 'Task Priority';
UPDATE `formats` SET `description` = 'Elige entre completar el trabajo o correr contra el reloj' WHERE `name` = 'Task Priority vs Time Priority';
UPDATE `formats` SET `description` = 'Series con velocidad controlada para maximizar tension muscular' WHERE `name` = 'Tempo Sets';
UPDATE `formats` SET `description` = 'Completa rondas lo mas rapido posible' WHERE `name` = 'Rounds for Time';
UPDATE `formats` SET `description` = 'Series con carga que sube y baja en oleadas progresivas' WHERE `name` = 'Wave Loading';
