-- @superseded-by 0087_widen_branch_code_and_fix_chapadmalal.sql
--
-- Original intent: insert "El Templo Chapadmalal" branch with 20 schedule rows.
-- Outcome: failed on production (strict SQL mode) and silently truncated on
-- staging to code "CHAPADMALA" because the code column was varchar(10) and the
-- intended code "CHAPADMALAL" is 11 chars.
--
-- 0087 widens the column to varchar(20), renames the truncated staging row,
-- and idempotently inserts the branch + schedules on envs that don't have them.
--
-- Kept as a no-op so production's migration runner records this file as applied
-- and advances to 0087. Do not delete — removing would cause inconsistent
-- migration history with staging, which already has this filename recorded in
-- its _migrations table.
